#!/usr/bin/env bash
# Regenerates the <!-- PROJECTS:START --> ... <!-- PROJECTS:END --> block in index.html
# with all public, non-archived, non-fork repos owned by USER that have GitHub Pages enabled.
# The Pages URL is detected via the API (handles user-page repos and custom CNAMEs).
#
# Deps: gh (authenticated), jq, awk
set -euo pipefail

USER="${USER_OVERRIDE:-artvandelay}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INDEX="$ROOT/index.html"

# Self-repo (the homepage repo itself) should be excluded from the list.
SELF_REPO="${SELF_REPO:-artvandelay.github.com}"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

echo "Fetching repos for $USER..." >&2

# Get all public, non-archived, non-fork, Pages-enabled repos.
gh api --paginate "users/$USER/repos?per_page=100&type=owner" \
  --jq '.[] | select(.has_pages and (.archived|not) and (.fork|not) and (.private|not)) | {name, description, html_url, updated_at}' \
  > "$tmp"

# For each repo, ask the Pages API for the canonical published URL (handles CNAMEs).
{
  echo "    <!-- PROJECTS:START -->"
  echo "    <!-- Auto-generated by scripts/generate.sh. Do not edit by hand. -->"
  # Read JSON lines, sort by updated_at desc.
  jq -s 'sort_by(.updated_at) | reverse | .[]' "$tmp" -c | while IFS= read -r line; do
    name=$(echo "$line" | jq -r '.name')
    [ "$name" = "$SELF_REPO" ] && continue
    desc=$(echo "$line" | jq -r '.description // ""')
    repo_url=$(echo "$line" | jq -r '.html_url')
    updated=$(echo "$line" | jq -r '.updated_at' | cut -c1-10)
    # Pages canonical URL.
    pages_url=$(gh api "repos/$USER/$name/pages" --jq '.html_url' 2>/dev/null || echo "")
    [ -z "$pages_url" ] && pages_url="https://$USER.github.io/$name/"
    # HTML-escape minimal chars.
    esc() { sed -e 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g'; }
    name_e=$(printf '%s' "$name" | esc)
    desc_e=$(printf '%s' "$desc" | esc)
    echo "    <li>"
    echo "      <a class=\"title\" href=\"$pages_url\">$name_e</a>"
    if [ -n "$desc" ]; then
      echo "      <p class=\"desc\">$desc_e</p>"
    fi
    echo "      <div class=\"meta\"><a href=\"$repo_url\">source</a><span>updated $updated</span></div>"
    echo "    </li>"
  done
  echo "    <!-- PROJECTS:END -->"
} > "$tmp.block"

# Replace block in index.html.
awk -v blockfile="$tmp.block" '
  BEGIN { while ((getline line < blockfile) > 0) block = block line "\n" }
  /<!-- PROJECTS:START -->/ { printing=0; printf "%s", block; skip=1; next }
  /<!-- PROJECTS:END -->/   { skip=0; next }
  skip { next }
  { print }
' "$INDEX" > "$INDEX.new"
mv "$INDEX.new" "$INDEX"

echo "Wrote $INDEX" >&2
